image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install && npm install -g eslint
    command: npm run start

ports:
  - name: Medblocks UI
    description: The Training Frontend of Medblocks UI
    port: 8080
    onOpen: open-browser
    visibility: private
